version: '3.4'

services:
    database_clinica:
        container_name: "database_clinica"
        image: postgres:14.1-alpine
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=MiGataSeLlamaGata
            - POSTGRES_DB=ClinicaVeterinariaTFG
        volumes:
            - database_clinica:/var/lib/postgresql/data

    clinica_veterinaria_api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "clinica_veterinaria_api"
        ports:
            - '1707:80'
            - '443:443'
        depends_on:
            - database_clinica
        environment:
            - ASPNETCORE_Kestrel__Endpoints__Https__Url=https://+:443;CertificatePath=/https/aspnetapp.pfx;CertificatePassword=clinicaveterinaria
        volumes:
            - ./aspnetapp.pfx:/https/aspnetapp.pfx

volumes:
    database_clinica: